### ISSUE TITLE
Do different weighting methods require different computations?

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/microdf#130]
As mentioned by @jdebacker today, do any of the weighted functions need to be adapted for different types of sample weights (inverse probability, etc.). Currently, weighted functions include:
* Mean
* Median
* Quantiles
* Gini index

@jdebacker, my understanding was that the different weight types have to do with statistical operations like regressions rather than these kinds of metrics, but please let me know if this is incorrect.

**Comment by jdebacker** [comment]
@MaxGhenis Yes, I think you are correct here that those weighted functions you use should yield the same results with frequency and probability weights without any modifications.

**Comment by MaxGhenis** [comment]
Thanks @jdebacker.
