### ISSUE TITLE
Subsetted MicroDataFrames are not MicroDataFrames

### ISSUE THREAD

**Issue by MaxGhenis** [PSLmodels/microdf#172]
MRE:
```
import microdf as mdf
df = mdf.MicroDataFrame({"x": [1, 2, 3]}, weights=[4, 5, 6])
df[df.x > 1].__class__
Out[4]: pandas.core.frame.DataFrame
```
This means there are no weights:
```
df[df.x > 1].weights
```
>AttributeError: 'DataFrame' object has no attribute 'weights'

And accordingly, functions over subsetted MicroDataFrames are not weighted (this should be `2 * 5 + 3 * 6 = 28`):
```
In [2]: df[df.x > 1].sum()
Out[2]: 
x    5
```

**Comment by nikhilwoodruff** [comment]
Fixed in #169
